name : "RandomForest"
input_data_path: "./data/raw/heart.csv"
output_model_path: "./models/RandomForest/model.pkl"
metric_path: "./models/RandomForest/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 42
  stratify:
model_params:
  model_type: "RandomForestClassifier"
metric_params:
    - "accuracy"
    - "roc_auc"  
feature_params:
  categorical:
    - "sex"
    - "cp"
    - "fbs"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical:
    - "age"
    - "trestbps"
    - "chol"
    - "restecg"
    - "thalach" 
    - "oldpeak"
  target: "target"
transformer_params:
  path: "./models/RandomForest/transformer.pkl"
