input_data_path: "./data/raw/heart.csv"
output_model_path: "./models/model_logistic.pkl"
metric_path: "./models/metrics_logistic.json"
splitting_params:
  val_size: 0.2
  random_state: 42
  stratify: "target"
train_params:
  model_type: "LogisticRegression"
metric_params:
    - "accuracy"
    - "roc_auc"
feature_params:
  categorical:
    - "sex"
    - "cp"
    - "fbs"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical:
    - "age"
    - "trestbps"
    - "chol"
    - "restecg"
    - "thalach" 
    - "oldpeak"
  target: "target"