model_folder : "RandomForest"
input_data_file: "heart.csv"
model_file: "model.pkl"
metric_file: "metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 21
  stratify: 'target'
  shuffle: True
model_params:
  model_type: "RandomForestClassifier"
  n_estimators : 300
metric_params:
    - "accuracy"
    - "roc_auc"
    - "f1"
feature_params:
  categorical:
    - "sex"
    - "cp"
    - "fbs"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical:
    - "age"
    - "trestbps"
    - "chol"
    - "restecg"
    - "thalach" 
    - "oldpeak"
  target: "target"
transformer_params:
  file:  "transformer.pkl"
logging_config: "logging.yaml"
